 export  const PROCESS_STEPS = [
    {
      id: 1,
      image: "/img/process-main.svg",
      title: "Intelligent Registration and Digital Records Management",
      roles: ["Administrator", "Employee"],
      desc: `Centralized system for registering cattle and managing livestock data digitally. Ensures accurate, up-to-date records covering identification, health, and ownership.`,
      stat: "91M+",
      statLabel: "Cattle Managed",
      statSub: "Empowering livestock at scale",
    },
    {
      id: 2,
      image: "/img/process-2.svg",
      title: "Daily Livestock Tracking and Performance Monitoring",
      roles: ["Administrator", "Employee"],
      desc: `Users record daily cattle activities, including care routines, feeding schedules, health checks, treatments, and other operational records. These ongoing updates help monitor cattle condition, detect potential issues early, and ensure optimal livestock management over time.`,
      stat: "87K+",
      statLabel: "Cooperative Farms",
      statSub: "Trusted farming network",
    },
    {
      id: 3,
      image: "/img/process-3.svg",
      title: "Integrated Livestock Health Inspection and Processing",
      roles: ["Abattoir", "Administrator"],
      desc: `Cattle undergo final health inspections to ensure safety and quality before slaughterhouse (RPH) processing and packaging. All inspection results, processing stages, and packaging details are recorded to maintain traceability, compliance, and product quality throughout distribution.`,
      stat: "32K+",
      statLabel: "Collaboration Abattoir",
      statSub: "Trusted by abattoir network",
    },
    {
      id: 4,
      image: "/img/process-4.svg",
      title: "Designing Simplified, End-to-End Customer Experiences",
      roles: ["Customer", "Abattoir"],
      desc: `A fully integrated livestock ecosystem transforming how infrastructure is planned, developed, and scaled through data-driven insights and seamless integration. Built to connect stakeholders, streamline operations, and enable smarter decisions across the livestock value chain while supporting sustainable growth and transparency.`,
      stat: "98+",
      statLabel: "Happy Customers",
      statSub: "Satisfied with Our Service",
    },
  ];